server:
  port: 8080

spring:
  application:
    name: blog-gateway

  cloud:
    gateway:
      routes:
        - id: statsroute
          uri: lb://STATS-SERVICE
          predicates:
            - Path=/api/stats/**
          filters:
            - RewritePath=/api(?<segment>.*), $\{segment}
            - name: Retry
              args:
                retries: 3
                statutes: INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
        - id: blogroute
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/api/blogs/**
          filters:
            - RewritePath=/api/blogs(?<segment>.*), $\{segment}
            - name: Retry
              args:
                retries: 3
                statutes: INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    # fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka